name: Pylint Code analysis

on:
  push:
    branches: ["main", "workflows"]
  pull_request:
    branches: ["main", "workflows"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pylint
        run: python -m pip install --upgrade pip pylint

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run linter
        run: pylint $(git ls-files '*.py')
