name: Pylint Code analysis

on:
  push:
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run linter
        run: pylint $(git ls-files '*.py')
